version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: todo-api
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/todo_db"
    ports:
      - "3001:3001"
    command: >
      sh -c "npx prisma migrate deploy && npm start"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
